name: CI - Validations

on:
  pull_request:
    branches: [master]
  push:
    branches:
      - 'master'

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'

    - name: Install dependencies
      run: dotnet restore 

    - name: Install SonarQube Cloud scanner
      run: dotnet tool install --global dotnet-sonarscanner

    - name: Add dotnet tools to PATH
      run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

    - name: Install Report Generator
      run: dotnet tool install -g dotnet-reportgenerator-globaltool

    - name: SonarCloud Scan - Begin
      run: |
        dotnet sonarscanner begin \
          /k:"LopesRebecca_ValidationsGeneral" \
          /o:"lopesrebecca" \
          /d:sonar.token="${{ secrets.SONAR_TOKEN }}" \
          /d:sonar.host.url="https://sonarcloud.io" \
          /d:sonar.cs.cobertura.reportsPaths="**/coverage.cobertura.xml"

    - name: Build
      run: dotnet build --no-restore --configuration Release
    
    - name: Install test SDK and collector
      run: |
        dotnet add ValidationsGeneral.Tests package Microsoft.NET.Test.Sdk --version 17.9.0
        dotnet add ValidationsGeneral.Tests package coverlet.collector

    - name: Run Tests with Coverage
      run: |
        dotnet test ValidationsGeneral.Tests/ValidationsGeneral.Tests.csproj \
          --collect:"XPlat Code Coverage" \
          --results-directory ./TestResults

    - name: Convert coverage to readable format
      run: |
        reportgenerator \
          -reports:TestResults/**/coverage.cobertura.xml \
          -targetdir:CoverageReport \
          -reporttypes:Html

    - name: SonarCloud Scan - End
      run: dotnet sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
