name: CI - Validations

on:
  pull_request:
    branches: [master]
  push:
    branches:
      - 'master'

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'

    - name: Install dependencies
      run: dotnet restore 

    - name: Install SonarQube Cloud scanner
      run: dotnet tool install --global dotnet-sonarscanner

    - name: Add dotnet tools to PATH
      run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH
      
    - name: SonarCloud Scan - Begin
      run: |
        dotnet sonarscanner begin \
          /k:"LopesRebecca_ValidationsGeneral" \
          /o:"lopesrebecca" \
          /d:sonar.token="${{ secrets.SONAR_TOKEN }}" \
          /d:sonar.host.url="https://sonarcloud.io" \
          /d:sonar.cs.opencover.reportsPaths="**/coverage.opencover.xml" \

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Run Tests with Coverage
      run: |
        dotnet test ValidationsGeneral.Tests/ValidationsGeneral.Tests.csproj \
           --collect:"XPlat Code Coverage" \
           --results-directory ./TestResults
    
    - name: Install Report Generator
      run: dotnet tool install -g dotnet-reportgenerator-globaltool
    
    - name: Convert coverage to readable format
      run: |
          reportgenerator \
           -reports:**/coverage.opencover.xml \
           -targetdir:CoverageReport \
           -reporttypes:Html

    - name: SonarCloud Scan - End
      run: dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
