name: Feature Validation

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restaure
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Tests
        run: dotnet test --no-build --configuration Release --collect:"XPlat Code Coverage"

      - name: SonarCloud
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
